### ISSUE TITLE
Remove banner

### ISSUE THREAD

**Issue by 6temes** [csvreader/csvreader#5]
Thank you for the great gem. It is really useful, especially when combined with CsvRecord.

Incidentally, as this gem has already reached version 1, would it be possible to remove the banner? It is quite noisy on the console.

https://github.com/csvreader/csvreader/blob/bf4015721a3668d648bd3dd323191daff9f28c55/lib/csvreader/base.rb#L168

**Comment by geraldb** [comment]
Good point. Changed to:

    puts CsvReader.banner    if $DEBUG

Will get out with the next gem update. Cheers. Prost.
