### ISSUE TITLE
[Enhancement] Allow passing options to Csv.strict.foreach

### ISSUE THREAD

**Issue by sgaxr** [csvreader/csvreader#6]
There is no convenient way to pass "strict" options such as `quote` to the `foreach` method:

> #> Csv.strict.foreach(file, sep: "-", quote: "#") { |row| pp row }
> ArgumentError: unknown keyword: quote

The only way I've found to do this is using the following:

> #> CsvReader::Builder.new(Csv::ParserStrict.new(sep: "-", quote: "#")).foreach(file) { |row| pp row }

This works, but it is very verbose and not at all intuitive.

**Comment by geraldb** [comment]
Good point. Good catch. Thanks for the suggestion. Will add the missing options to `foreach`.

**Comment by geraldb** [comment]
Hello, I changed all builders to allow any keyword args e.g.:
      def foreach( path, **kwargs, &block )
         CsvReader.foreach( path, parser: @parser, **kwargs, &block )
      end

However, in your case the ParserStrict.parse only supports the "dynamic" sep argument, see

     def parse( data, sep: config[:sep], &block )

> There is no convenient way to pass "strict" options such as quote 
Anyways, yes there is a convenient way to to pass "strict" options such as quote along :-)  Use:

    Csv.strict.config[:quote] = "#"
    Csv.strict.config[:doublequote] = false
    Csv.strict.foreach(file, sep: "-" ) { |row| pp row }
    Csv.strict.foreach(file, sep: "-" ) { |row| pp row }
    ...

Note, you can also set sep to "-" as your default e.g.

    Csv.strict.config[:sep] = "-"
    Csv.strict.foreach(file ) { |row| pp row }

Does this work for you? Not sure if I will add the options to parse itself (the parser needs to get reworked, see <https://github.com/csvreader/csvreader/blob/master/lib/csvreader/parser_strict.rb>. Cheers. Prost.

**Comment by sgaxr** [comment]
Hey, sorry, didn't see this. That looks awesome. Thanks!

**Comment by geraldb** [comment]
No worries. It isn't really documented. Thanks for trying csvreader. Cheers. Prost.
