### ISSUE TITLE
CsvReader::ParseError: found >1 (49)< - FS (,) or RS (\n) expected!!!!

### ISSUE THREAD

**Issue by waruboy** [csvreader/csvreader#7]
Hello! First, thank you for the gem, I use it on one of my project in production for our csv upload feature.

[test.txt](https://github.com/csvreader/csvreader/files/2872079/test.txt)
When I try to read attached file using CsvReader.read , I got following error:
CsvReader::ParseError: found >1 (49)< - FS (,) or RS (\n) expected!!!!

(The alphabet on the original file has been replaced by "1" to protect the content, but the error remains)
The standard ruby library CSV.read is able to read this file.

How can I handle this error?

**Comment by geraldb** [comment]
Your test.txt is an invalid csv file in line 12:

     '1 11111 111111 & 111111111111111;111111111;4;8531 11;111111;;11;11111111;

It starts with an opening quote `'` but the closing quote is missing - thus, the error. If you do NOT use quotes in your format, use a different parser:

     require 'csvreader'
     pp Csv.table.read( 'test.txt', sep: ';' )

Works. Because there a no escape quote rules in the csv table variant. Cheers. Prost.

**Comment by waruboy** [comment]
Thank you!

**Comment by waruboy** [comment]
Sorry for continuing.
I tried to add the case to my test suite, but find this

```
a = "a;b\n'c;d\ne;f"

Csv.parse a, sep: ";"

=> [["a", "b"], ["c;d\ne;f"]]
```

No exception raised. Is there anything else going on?

**Comment by geraldb** [comment]
Again you're missing the closing quote - everthing gets added / slurrped into the last field.
Try:  `a = "a;b\n'c;d\ne;f'gg"`  And you will get your exception because after the closing quote a semicolon (;) is expected.

**Comment by waruboy** [comment]
@geraldb Ah I think I understand know. So what raise the exception in my file was because there is another quote `'` in lines after 12, so it become closing quote, and it was not followed be a linebreak or column separator.

Thank you for your help and your patience. And once again thank you for the gem! It saves me a lot of time in handling CSV edge cases.

**Comment by geraldb** [comment]
Yes, that's my understanding too. Thanks for your kind words. Cheers. Prost. Sorry - I know the error is still missing the line number (for now) - needs to get added in an update.
