### ISSUE TITLE
How do I get different file encodings?

### ISSUE THREAD

**Issue by RomanADavis** [csvreader/csvreader#8]
`C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/csvreader-1.2.4/lib/csvreader/parser_std.rb:324:in `sub': invalid byte sequence in UTF-8 (ArgumentError)`

**Comment by geraldb** [comment]
Please, use the forum / mailing list for support questions, see <http://groups.google.com/group/wwwmake>   You can use open - it is a "mirror" or File.open and pass along your own encoding.
